In [ ]:
import pandas as pd
import numpy as np

In [ ]:
pb=pd.read_csv('QVI_purchase_behaviour.csv')
td=pd.read_excel('QVI_transaction_data.xlsx')

In [ ]:
pb.head()

   LYLTY_CARD_NBR               LIFESTAGE PREMIUM_CUSTOMER
0            1000   YOUNG SINGLES/COUPLES          Premium
1            1002   YOUNG SINGLES/COUPLES       Mainstream
2            1003          YOUNG FAMILIES           Budget
3            1004   OLDER SINGLES/COUPLES       Mainstream
4            1005  MIDAGE SINGLES/COUPLES       Mainstream

In [ ]:
td.head()

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES
0,43390,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0
1,43599,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3
2,43605,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9
3,43329,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0
4,43330,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8

In [ ]:
pb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72637 entries, 0 to 72636
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   LYLTY_CARD_NBR    72637 non-null  int64
 1   LIFESTAGE         72637 non-null  object
 2   PREMIUM_CUSTOMER  72637 non-null  object
dtypes: int64(1), object(2)
memory usage: 1.7+ MB

In [ ]:
td.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264836 entries, 0 to 264835
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DATE            264836 non-null  int64
 1   STORE_NBR       264836 non-null  int64
 2   LYLTY_CARD_NBR  264836 non-null  int64
 3   TXN_ID          264836 non-null  int64
 4   PROD_NBR        264836 non-null  int64
 5   PROD_NAME       264836 non-null  object
 6   PROD_QTY        264836 non-null  int64
 7   TOT_SALES       264836 non-null  float64
dtypes: float64(1), int64(6), object(1)
memory usage: 16.2+ MB

In [ ]:
pb.isnull().sum()

LYLTY_CARD_NBR      0
LIFESTAGE           0
PREMIUM_CUSTOMER    0
dtype: int64

In [ ]:
td.isnull().sum()

DATE              0
STORE_NBR         0
LYLTY_CARD_NBR    0
TXN_ID            0
PROD_NBR          0
PROD_NAME         0
PROD_QTY          0
TOT_SALES         0
dtype: int64

In [ ]:
td.DATE=pd.to_datetime("1899-12-30") + pd.to_timedelta(td.DATE, unit="D")

In [ ]:
td.describe()

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_QTY,TOT_SALES
count,264836,264836.00000,2.648360e+05,2.648360e+05,264836.000000,264836.000000,264836.000000
mean,2018-12-30 00:52:12.879215616,135.08011,1.355495e+05,1.351583e+05,56.583157,1.907309,7.304200
min,2018-07-01 00:00:00,1.00000,1.000000e+03,1.000000e+00,1.000000,1.000000,1.500000
25%,2018-09-30 00:00:00,70.00000,7.002100e+04,6.760150e+04,28.000000,2.000000,5.400000
50%,2018-12-30 00:00:00,130.00000,1.303575e+05,1.351375e+05,56.000000,2.000000,7.400000
75%,2019-03-31 00:00:00,203.00000,2.030942e+05,2.027012e+05,85.000000,2.000000,9.200000
max,2019-06-30 00:00:00,272.00000,2.373711e+06,2.415841e+06,114.000000,200.000000,650.000000
std,NaN,76.78418,8.057998e+04,7.813303e+04,32.826638,0.643654,3.083226

In [ ]:
td.loc[td.PROD_QTY>50]

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES
69762,2018-08-19,226,226000,226201,4,Dorito Corn Chp Supreme 380g,200,650.0
69763,2019-05-20,226,226000,226210,4,Dorito Corn Chp Supreme 380g,200,650.0

In [ ]:
td=td[td.PROD_QTY!=200]

In [ ]:
td['PACK_SIZE']=td['PROD_NAME'].str.extract(pat='([0-9]+g)')

In [ ]:
td[['PROD_NAME','PACK_SIZE']].head()

                                  PROD_NAME PACK_SIZE
0    Natural Chip        Compny SeaSalt175g      175g
1                  CCs Nacho Cheese    175g      175g
2    Smiths Crinkle Cut  Chips Chicken 170g      170g
3    Smiths Chip Thinly  S/Cream&Onion 175g      175g
4  Kettle Tortilla ChpsHny&Jlpno Chili 150g      150g

In [ ]:
td['PACK_SIZE'] = pd.to_numeric(td['PACK_SIZE'].str.replace('g', ''), errors='coerce')

In [ ]:
td['PACK_SIZE'].head(10)

0    175.0
1    175.0
2    170.0
3    175.0
4    150.0
5    300.0
6    330.0
7    210.0
8    150.0
9      NaN
Name: PACK_SIZE, dtype: float64

In [ ]:
td['PACK_SIZE'].isnull().sum()

np.int64(6064)

In [ ]:
td.dtypes

DATE              datetime64[ns]
STORE_NBR                  int64
LYLTY_CARD_NBR             int64
TXN_ID                     int64
PROD_NBR                   int64
PROD_NAME                 object
PROD_QTY                   int64
TOT_SALES                float64
PACK_SIZE                float64
dtype: object

In [ ]:
td['BRAND']=td.PROD_NAME.str.split().str[0]

In [ ]:
td[['PROD_NAME','BRAND']].head()

                                  PROD_NAME    BRAND
0    Natural Chip        Compny SeaSalt175g  Natural
1                  CCs Nacho Cheese    175g      CCs
2    Smiths Crinkle Cut  Chips Chicken 170g   Smiths
3    Smiths Chip Thinly  S/Cream&Onion 175g   Smiths
4  Kettle Tortilla ChpsHny&Jlpno Chili 150g   Kettle

In [ ]:
all_data=pd.merge(td, pb, on='LYLTY_CARD_NBR', how="inner")

In [ ]:
all_data.head()

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES,PACK_SIZE,BRAND,LIFESTAGE,PREMIUM_CUSTOMER
0,2018-10-17,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0,175.0,Natural,YOUNG SINGLES/COUPLES,Premium
1,2019-05-14,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3,175.0,CCs,MIDAGE SINGLES/COUPLES,Budget
2,2019-05-20,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9,170.0,Smiths,MIDAGE SINGLES/COUPLES,Budget
3,2018-08-17,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0,175.0,Smiths,MIDAGE SINGLES/COUPLES,Budget
4,2018-08-18,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8,150.0,Kettle,MIDAGE SINGLES/COUPLES,Budget

In [ ]:
all_data.shape

(264834, 12)

In [ ]:
all_data.TOT_SALES.sum()

np.float64(1933115.0000000002)

In [ ]:
all_data.PROD_QTY.sum()

np.int64(504724)

In [ ]:
group=all_data.groupby(['LIFESTAGE','PREMIUM_CUSTOMER']).agg({'TOT_SALES': 'sum','PROD_QTY': 'sum'}).sort_values('TOT_SALES', ascending=False)

In [ ]:
group

                                         TOT_SALES  PROD_QTY
LIFESTAGE              PREMIUM_CUSTOMER
OLDER FAMILIES         Budget            168363.25     45065
YOUNG SINGLES/COUPLES  Mainstream        157621.60     38632
RETIREES               Mainstream        155677.05     40518
YOUNG FAMILIES         Budget            139345.85     37111
OLDER SINGLES/COUPLES  Budget            136769.80     35220
                       Mainstream        133393.80     34997
                       Premium           132263.15     33986
RETIREES               Budget            113147.80     28764
OLDER FAMILIES         Mainstream        103445.55     27756
RETIREES               Premium            97646.05     24884
YOUNG FAMILIES         Mainstream         92788.75     25044
MIDAGE SINGLES/COUPLES Mainstream         90803.85     22699
YOUNG FAMILIES         Premium            84025.50     22406
OLDER FAMILIES         Premium            80658.40     21771
YOUNG SINGLES/COUPLES  Budget             61141.60     16671
MIDAGE SINGLES/COUPLES Premium            58432.65     15526
YOUNG SINGLES/COUPLES  Premium            41642.10     11331
MIDAGE SINGLES/COUPLES Budget             35514.80      9496
NEW FAMILIES           Budget             21928.45      5571
                       Mainstream         17013.90      4319
                       Premium            11491.10      2957

In [ ]:
all_data.loc[(all_data.LIFESTAGE == 'OLDER FAMILIES') & (all_data.PREMIUM_CUSTOMER == 'Budget')].groupby("BRAND").agg({'TOT_SALES': 'sum'})

            TOT_SALES
BRAND
Burger         692.30
CCs           1852.20
Cheetos       1687.40
Cheezels      3723.00
Cobs          5658.20
Dorito        3123.25
Doritos      17041.70
French         828.00
Grain         3510.00
GrnWves        995.10
Infuzions     6313.00
Infzns        2052.00
Kettle       32058.00
NCC            957.00
Natural       3366.00
Old           7568.40
Pringles     14300.50
RRD           6798.00
Red           3364.20
Smith         1549.60
Smiths       20101.50
Snbts          532.10
Sunbites       470.90
Thins         7517.40
Tostitos      6006.00
Twisties      7164.60
Tyrrells      4002.60
WW            3786.60
Woolworths    1343.70

In [ ]:
all_data['BRAND'] = all_data['BRAND'].replace({
    'Dorito': 'Doritos',
    'Smith': 'Smiths',
    'Infzns': 'Infuzions',
    'Snbts': 'Sunbites',
    'Red': 'RRD',
    'GrnWves': 'Grain',
    'WW': 'Woolworths'
})

In [ ]:
all_data.loc[
    (all_data.LIFESTAGE == 'OLDER FAMILIES') &
    (all_data.PREMIUM_CUSTOMER == 'Budget')
].groupby("BRAND").agg({'TOT_SALES': 'sum'}).sort_values('TOT_SALES', ascending=False)

            TOT_SALES
BRAND
Kettle       32058.00
Smiths       21651.10
Doritos      20164.95
Pringles     14300.50
RRD          10162.20
Infuzions     8365.00
Old           7568.40
Thins         7517.40
Twisties      7164.60
Tostitos      6006.00
Cobs          5658.20
Woolworths    5130.30
Grain         4505.10
Tyrrells      4002.60
Cheezels      3723.00
Natural       3366.00
CCs           1852.20
Cheetos       1687.40
Sunbites      1003.00
NCC            957.00
French         828.00
Burger         692.30

In [ ]:
all_data.loc[
    (all_data.LIFESTAGE == 'OLDER FAMILIES') &
    (all_data.PREMIUM_CUSTOMER == 'Budget')
].groupby("PACK_SIZE").agg({'TOT_SALES': 'sum'}).sort_values('TOT_SALES', ascending=False)

           TOT_SALES
PACK_SIZE
175.0       41346.70
150.0       26093.70
134.0       14300.50
110.0       13360.80
170.0       13050.70
330.0       12152.40
300.0        9983.30
165.0        8994.20
380.0        6114.55
270.0        4825.40
250.0        2339.20
135.0        2213.40
210.0        1778.40
200.0        1639.70
190.0        1548.00
160.0        1128.60
90.0         1003.00
180.0         995.10
220.0         692.30
70.0          662.40
125.0         627.90

In [ ]:
all_data

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES,PACK_SIZE,BRAND,LIFESTAGE,PREMIUM_CUSTOMER
0,2018-10-17,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0,175.0,Natural,YOUNG SINGLES/COUPLES,Premium
1,2019-05-14,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3,175.0,CCs,MIDAGE SINGLES/COUPLES,Budget
2,2019-05-20,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9,170.0,Smiths,MIDAGE SINGLES/COUPLES,Budget
3,2018-08-17,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0,175.0,Smiths,MIDAGE SINGLES/COUPLES,Budget
4,2018-08-18,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8,150.0,Kettle,MIDAGE SINGLES/COUPLES,Budget
...,...,...,...,...,...,...,...,...,...,...,...,...
264829,2019-03-09,272,272319,270088,89,Kettle Sweet Chilli And Sour Cream 175g,2,10.8,175.0,Kettle,YOUNG SINGLES/COUPLES,Premium
264830,2018-08-13,272,272358,270154,74,Tostitos Splash Of Lime 175g,1,4.4,175.0,Tostitos,YOUNG SINGLES/COUPLES,Premium
264831,2018-11-06,272,272379,270187,51,Doritos Mexicana 170g,2,8.8,170.0,Doritos,YOUNG SINGLES/COUPLES,Premium
264832,2018-12-27,272,272379,270188,42,Doritos Corn Chip Mexican Jalapeno 150g,2,7.8,150.0,Doritos,YOUNG SINGLES/COUPLES,Premium
264833,2018-09-22,272,272380,270189,74,Tostitos Splash Of Lime 175g,2,8.8,175.0,Tostitos,YOUNG SINGLES/COUPLES,Premium